language: php

cache: apt

php:
  #- 5.4
  - 5.5

mysql:
  database: drupal
  username: root
  encoding: utf8

install:
  # Install Apache
  - sudo apt-get install apache2 libapache2-mod-fastcgi

  # Configure PHP
  - echo -e "opcache.enable_cli=1\ncgi.fix_pathinfo=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # Configure Apache
  - sudo cp -f $TRAVIS_BUILD_DIR/.travis/apache-vhost.conf /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$TRAVIS_BUILD_DIR/../drupal?g" --in-place /etc/apache2/sites-available/default
  - sudo a2enmod rewrite actions fastcgi alias && sudo service apache2 restart

  # Download Drush and Drupal
  - composer global require drush/drush:dev-master
  - git clone --depth 1 --branch 8.0.x http://git.drupal.org/project/drupal.git $TRAVIS_BUILD_DIR/../drupal

  # Download dependencies
#  - git clone --depth 1 --branch 8.x-1.x http://git.drupal.org/project/multiversion.git modules/multiversion
#  - git clone --depth 1 --branch 8.x-1.x http://git.drupal.org/project/key_value.git modules/key_value
  - git clone --branch 8.0.x-compatibility https://github.com/dickolsson/drupal-key_value.git $TRAVIS_BUILD_DIR/../drupal/modules/key_value
  - git clone --branch 8.0.x-compatibility https://github.com/dickolsson/drupal-multiversion.git $TRAVIS_BUILD_DIR/../drupal/modules/multiversion
  - ln -s $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../drupal/modules/relaxed

  # Install the host site
  - php -d sendmail_path=`which true` ~/.composer/vendor/bin/drush.php --yes site-install --db-url=mysql://root:@127.0.0.1/drupal testing
  - drush --yes pm-enable relaxed


script:
  # Enable Simpletest and run Simpletest tests.
  - drush en --yes simpletest
  - drush cr
  - cd $TRAVIS_BUILD_DIR/../drupal
  - php core/scripts/run-tests.sh --verbose --color --concurrency 4 --php `which php` --url http://localhost "relaxed" | tee /tmp/test.txt ; export TEST_EXIT=${PIPESTATUS[0]} ; echo $TEST_EXIT
  # Simpletest does not exit with code 0 on success, so we will need to analyze
  # the output to ascertain whether the tests passed.
  - TEST_SIMPLETEST=$(! egrep -i "([0-9]+ fails)|(PHP Fatal error)|([0-9]+ exceptions)" /tmp/test.txt > /dev/null)$?
  - sudo cat /var/log/apache2/error.log
  - echo $TEST_EXIT
  - echo $TEST_SIMPLETEST
  - if [ $TEST_EXIT -eq 0 ] && [ $TEST_SIMPLETEST -eq 0 ]; then exit 0; else exit 1; fi
